---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: raven
# description will be included in the image's metadata
description: "Raven - Simplified Bazzite-Gnome for AMD desktop."
# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/silverblue-main
image-version: latest

modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
    install:
      - micro
      - starship
    remove:
      - firefox
      - firefox-langpacks
      - waydroid
      - webapp-manager
      - tailscale
      - sunshine
      - vim
      - cockpit
      - cockpit-networkmanager
      - cockpit-podman
      - cockpit-selinux
      - cockpit-system
      - cockpit-navigator
      - cockpit-storaged

  - type: default-flatpaks
    notify: true
    system: # Default Flathub
      install:
        - org.mozilla.firefox
        - org.gnome.Loupe
        - com.spotify.Client
      remove:
        - org.gnome.eog
    user: {}

  - type: signing

